version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./sanga/uploads:/var/www/html/uploads
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=sanga_user
      - DB_PASSWORD=sanga_pass
      - DB_NAME=chat
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: chat
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: sanga_user
      MYSQL_PASSWORD: sanga_pass
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  # Runs initialization scripts
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge

